export const JAM_MEM_COVER_ASPECT_RATIO = 1.25; // 5:4 height:width

export const JAM_MEM_COVER_WIDTH = 360;

export const JAM_MEM_COVER_HEIGHT =
    JAM_MEM_COVER_WIDTH * JAM_MEM_COVER_ASPECT_RATIO;
