const HOUR_MILLISECONDS = 60 * 60 * 1000;

export const LOCATION_UPDATE_INTERVAL = 10_000;

export const POST_SNAPSHOTS_INTERVAL = 0.5 * HOUR_MILLISECONDS;

export const POST_SNAPSHOTS_COOLDOWN = 60 * 1000;

export const JAM_MEM_QUERY_STALE_TIME = 12 * HOUR_MILLISECONDS;

export const CLUSTERS_QUERY_STALE_TIME = 0.5 * HOUR_MILLISECONDS;

export const PENDING_REQUESTS_QUERY_STALE_TIME = 0.5 * HOUR_MILLISECONDS;
