# 🔗 Links:
# Source file: https://github.com/obytes/react-native-template-obytes/blob/master/.github/actions/setup-node-pnpm-install/action.yml

name: "Setup  Node + PNPM + Install Dependencies"
description: "Setup  Node + PNPM + Install Dependencies"
runs:
    using: "composite"
    steps:
        - uses: pnpm/action-setup@v2
          with:
              version: "^9.0.6"
        - uses: actions/setup-node@v3
          with:
              cache: "pnpm"

        - name: 📦 Install Project Dependencies
          run: pnpm install --frozen-lockfile
          shell: bash
